spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fooddb?serverTimezone=UTC&characterEncoding=UTF-8
    username: fooddbuser
    password: fooddbpassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    springJr.foodbasket: debug
    org.hibernate.SQL: debug # ?? log? ??
    org.hibernate.type: debug